
language: node_js

node_js:
  - "10"

branches:
  only:
    - master

notifications:
  webhooks:
    urls:
      - https://oapi.dingtalk.com/robot/send?access_token=db2c41758f3def878e395308a96948c8581be27b7996622105910dab05fdb76c
    on_success: always
    on_failure: always

install:
  - yarn

script:
  yarn build

deploy:
  provider: pages
  local_dir: dist
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master

cache:
  directories:
    - node_modules