
language: node_js

node_js:
  - "10"

branches:
  only:
    - master

notifications:
  webhooks: https://oapi.dingtalk.com/robot/send?access_token=15ebd4169a27e4c3150a8d1584566d0938ae4e4ad09f7d4664bdb32cd38ff376

install:
  - yarn

script:
  yarn build

deploy:
  provider: pages
  local_dir: dist
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master

cache:
  directories:
    - node_modules